"use client";
import { useState, type FormEvent, type ReactNode } from "react";
import { useRouter } from "next/navigation";
import { allocateSerial, approveProfile, registerInventorySerial, shipAllocation } from "@/lib/oh/commands";
import styles from "@/app/page.module.css";

export type AdminWorkspaceProps = { pendingProfiles: Array<{ id: string; employee_id: string; created_at: string }>; requests: Array<{ id: string; partner_code: string; requested_model: string; quantity: number; status: string; created_at: string }>; inventory: Array<{ id: string; model_code: string; serial_number: string; storage_location: string | null; status: string }>; allocations: Array<{ id: string; status: string; allocated_at: string; requests: { partner_code: string; requested_model: string }; inventory_serials: { serial_number: string; model_code: string } }> };
const labels = ["가입 승인", "요청 관리", "SN 재고", "OH 배정", "출고 관리"] as const; type Tab = typeof labels[number];
export function AdminWorkspace(props: AdminWorkspaceProps) {
  const router = useRouter(); const [tab, setTab] = useState<Tab>("가입 승인"); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function act(promise: Promise<{ error?: string }>, success: string) { setError(""); setMessage(""); const result = await promise; if (result.error) setError(result.error); else { setMessage(success); router.refresh(); } }
  function submitInventory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); void act(registerInventorySerial(String(f.get("model")), String(f.get("serial")), String(f.get("location"))), "SN 재고를 등록했습니다."); event.currentTarget.reset(); }
  function submitAllocation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); void act(allocateSerial(String(f.get("request")), String(f.get("serial"))), "SN을 배정했습니다."); }
  function submitShipment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); void act(shipAllocation(String(f.get("allocation")), String(f.get("date")), Number(f.get("revenue")), String(f.get("note"))), "출고를 처리했습니다."); }
  return <main className={styles.workspaceMain}><header className={styles.header}><div className={styles.brand}><span className={styles.brandMark}>OH</span><span>OH 관리<small className={styles.brandSub}>ADMIN WORKSPACE</small></span></div></header><section className={styles.main}><nav className={styles.tabNav} aria-label="관리 메뉴">{labels.map((label) => <button key={label} aria-current={tab === label ? "page" : undefined} className={tab === label ? styles.activeNav : undefined} onClick={() => setTab(label)}>{label}</button>)}</nav>{error && <p className={styles.formError} role="alert">{error}</p>}{message && <p className={styles.formSuccess} role="status">{message}</p>}
    {tab === "가입 승인" && <Table title="가입 승인" rows={props.pendingProfiles} columns={["사번", "신청일", "처리"]} render={(row) => <><th>{row.employee_id}</th><td>{row.created_at.slice(0, 10)}</td><td><button onClick={() => void act(approveProfile(row.id), "가입을 승인했습니다.")}>승인</button></td></>} />}
    {tab === "요청 관리" && <Table title="OH 요청 관리" rows={props.requests} columns={["ITSS CODE", "기종", "수량", "상태"]} render={(row) => <><th>{row.partner_code}</th><td>{row.requested_model}</td><td>{row.quantity}</td><td>{row.status}</td></>} />}
    {tab === "SN 재고" && <><section className={styles.requestFormPanel}><form className={styles.requestForm} onSubmit={submitInventory}><label>기종<input name="model" required /></label><label>SN<input name="serial" required /></label><label className={styles.fullWidth}>보관 위치<input name="location" /></label><div className={styles.formActions}><button>SN 등록</button></div></form></section><Table title="SN 재고 현황" rows={props.inventory} columns={["기종", "SN", "보관 위치", "상태"]} render={(row) => <><th>{row.model_code}</th><td>{row.serial_number}</td><td>{row.storage_location ?? "-"}</td><td>{row.status}</td></>} /></>}
    {tab === "OH 배정" && <section className={styles.requestFormPanel}><form className={styles.requestForm} onSubmit={submitAllocation}><label>요청<select name="request">{props.requests.filter((row) => !["SHIPPED", "CANCELLED"].includes(row.status)).map((row) => <option key={row.id} value={row.id}>{row.partner_code} · {row.requested_model} · {row.quantity}대</option>)}</select></label><label>배정할 SN<select name="serial">{props.inventory.filter((row) => row.status === "AVAILABLE").map((row) => <option key={row.id} value={row.serial_number}>{row.model_code} · {row.serial_number}</option>)}</select></label><div className={styles.formActions}><button>SN 배정</button></div></form></section>}
    {tab === "출고 관리" && <section className={styles.requestFormPanel}><form className={styles.requestForm} onSubmit={submitShipment}><label>배정 SN<select name="allocation">{props.allocations.filter((row) => row.status === "ALLOCATED").map((row) => <option key={row.id} value={row.id}>{row.inventory_serials.serial_number} · {row.requests.partner_code}</option>)}</select></label><label>출고일<input name="date" type="date" required /></label><label>매출<input name="revenue" type="number" min="0" defaultValue="0" required /></label><label>비고<input name="note" /></label><div className={styles.formActions}><button>출고 처리</button></div></form></section>}
  </section></main>;
}
function Table<T extends { id: string }>({ title, rows, columns, render }: { title: string; rows: T[]; columns: string[]; render: (row: T) => ReactNode }) { return <section className={styles.panel}><div className={styles.panelHeading}><h1>{title}</h1></div><table><thead><tr>{columns.map((column) => <th key={column}>{column}</th>)}</tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id}>{render(row)}</tr>) : <tr><td colSpan={columns.length}>표시할 데이터가 없습니다.</td></tr>}</tbody></table></section>; }
